layout_spectrum: 0.5827235449105501
typography_spectrum: 0.4283552479464561
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.21573519799858332
  lightness: 0.7073965796735138
  saturation: 0.16044786502607167
  rhythmicContrast: 0.039009531727060676
content_rating:
  adult: false
opengraph:
  type: ''
  appId: ''
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/979c1fc8-6edd-4e1a-917e-485bed0d3d10.jpg
name: Ascent
navigation:
  - name: Home
    id: 7113a44a-e126-450a-8b12-3a6d2284235c
    type: content
  - name: Articles
    id: 5d5fffe7-81fa-4fb5-86a4-eaaca87c4ace
    type: content
  - name: About us
    id: 3a6f95fe-6865-46fa-9f97-ce4d3702dcb2
    type: content
title: looking for clarity in an unclear world
description: ''
