typography_spectrum: 0.2832196488315998
content_rating:
  adult: false
color:
  brandColors:
    - '#E7E8D1'
    - '#D3CEAA'
    - '#FBF7E4'
    - '#424242'
    - '#8E001C'
  brandStrength: 0.3478937823945125
  lightness: 0.24680655606794677
  saturation: 0.3235582265768948
  rhythmicContrast: 0.15686724257289075
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.8876692840548038
author:
  name: ''
  url: ''
  email: ''
name: Ascent
navigation:
  - name: About us
    id: 7113a44a-e126-450a-8b12-3a6d2284235c
    type: content
title: Ascent
description: looking for clarity in an unclear world
